### ISSUE TITLE
Stabilize `EStr<Path>::segments`

### ISSUE THREAD

**Issue by the-kenny** [yescallop/fluent-uri-rs#14]
Thanks for picking up development of this library again!

I'm in a situation where I forced `fluent_uri` some time ago to implement `PartialEq` etc. for `Uri<_>`. With your recent changes I'm almost able to use the upstream repository again.

One thing missing is `uri.path().segments()` is guarded behind `#[cfg(fluent_uri_unstable)]`. Do you have any plans on stabilising this or a similar method soon?

Another option might be getting rid of the custom cfg-attribute and putting it behind a `unstable` feature.

**Comment by yescallop** [comment]
The reason why I unstabilized the method was that I feared it would be a footgun. For example, I found that [this usage](https://github.com/RGB-WG/rgb-std/blob/9e23bd272a989c5f0315f458565abfe3c1f7b2a0/invoice/src/parse.rs#L333) of `segments` allows both absolute and rootless paths, which might be unintended. Users may think that the return value of `segments` uniquely identifies a path, but this isn't the case as the empty string before a preceding `'/'` does not count as a segment.

I think that the current behavior of `segments` is not bad, but it needs to be more explicitly documented. So I went on to stabilize it in a recent commit. I also expanded its doc so that it's less likely to be misused.

That said, things may still change before the next release. Would you mind sharing your use case for `segments` so that I can make better decisions? Thanks for your attention to this library.

**Comment by yescallop** [comment]
I have published a new release of version `0.2.0-alpha.6` with `EStr<Path>::segments` stabilized. Thanks for bringing this up!

If you have other questions or suggestions don't hesitate to open another issue. I'll continue to make sure this library offers a good user experience.

**Comment by yescallop** [comment]
Hi,

I decided to make `EStr<Path>::segments` return `Option` instead in a recent [commit](https://github.com/yescallop/fluent-uri-rs/commit/7e478aa374b2007d9ce6514ae3f614bc92a22461). It now returns `None` when the path is rootless (does not start with `/`), in which case one can use `EStr::split` instead. I believe that this change will make it less likely for users to misuse the method.
