### ISSUE TITLE
Extending `EString` API

### ISSUE THREAD

**Issue by Stranger6667** [yescallop/fluent-uri-rs#29]
In `jsonschema` I need to encode quite a lot of different strings and it will be nice to reuse the buffer (methods like `clear` and `with_capacity` would be useful) or, maybe encode to some provided buffer without unconditional allocation. Otherwise allocations from the `EString` popup quite a lot in flamegraphs.

Would you be open to exposing an API that will allow you to perform encoding without unconditionally allocating a buffer?

**Comment by Stranger6667** [comment]
Looks interesting! I am inclined to the latter option, as in my use case I need to manipulate fragments quite a lot. Most of the things are either about building an [absolute keyword location](https://json-schema.org/draft/2020-12/json-schema-core#section-12.3.2) or looking things up during reference resolution. I’ll provide some more details soon

**Comment by yescallop** [comment]
Thanks for your explanation! You are correct that resolving a fragment-only reference is equivalent to setting the fragment. I have added the `with_fragment` and `set_fragment` methods and published a new version `0.3.2`. Hope that it helps!

**Comment by Stranger6667** [comment]
Amazing! That was fast! I changed the code so it uses `with_fragment` and there are [up to ~50%](https://codspeed.io/Stranger6667/jsonschema-rs/branches/dd/update-uris) improvements in validation performance :) Thank you so much for such a quick implementation & response!

**Comment by yescallop** [comment]
Glad to know it helps this much! I should note that there are improvements you can make by encoding to an `EString<Fragment>` and passing it directly to `with_fragment`, and by changing the code [here](https://github.com/Stranger6667/jsonschema-rs/blob/a9ffe738a30943455a1e5ddbb83e35b357144f19/crates/jsonschema-referencing/src/registry.rs#L430-L439) to use `set_fragment` instead (not sure why the query component isn't included, was it intentional?)

I'll consider this issue as closed now. Feel free to ask if you have more questions :)
