### ISSUE TITLE
Make ParseError attributes public

### ISSUE THREAD

**Issue by Anatoly03** [yescallop/fluent-uri-rs#30]
The [ParseError](https://github.com/yescallop/fluent-uri-rs/blob/0a6e4b280bc20a8631bbd1fa70c68b9768f8319c/src/error.rs#L26) implementations currently hide all attributes to the crate. This is unfortunate, as it limits the usage of this crate as a Parser utility.

https://github.com/yescallop/fluent-uri-rs/blob/0a6e4b280bc20a8631bbd1fa70c68b9768f8319c/src/error.rs#L26-L30

Alternatively, a method `force_input()` could be created, with signature `(self) -> (UriRef<Input>, Input)` and generic `Input`. This would split the error into two strings: valid read Uri/Iri/UriRef/IriRef and the rest string.

Another idea is to have a method that exposes the `index` attribute so the above behaviour can be implemented by the crate user.

Visualization:

```rs
"GET /hello/world HTTP/1.1"
 ^^^^                        Custom Implementation
     ^^^^^^^^^^^^            Uri::parse().force_input() // Uri converts this part
                 ^^^^^^^^^   // Rest string, consumable for further parsing.
```

There are also other requests to expose more internal datastructures: https://github.com/yescallop/fluent-uri-rs/issues/18

This issue aside, thank you very much for creating the crate! Wonderful!

**Comment by yescallop** [comment]
I'm open to adding an `index` method to `ParseError`, but one thing to note is that the input string is not always valid as a URI/IRI up to this index. For example, `Uri::parse("foo")` returns an error at index 3, but `foo` is not a valid URI, nor is any of its prefixes. Nevertheless, it is always possible to find a prefix of a given string that is a valid URI/IRI reference.

As a result, it might not be very helpful to only add an `index` method. An extra `valid_up_to` method which returns an `Option<usize>` could be what you need. However...

As for the `GET /hello/world HTTP/1.1` example, one can split the string on spaces first and try to parse the second slice as a URI, which I think is more straightforward and efficient than to, say, try to parse `/hello/world HTTP/1.1`, get an error, call `valid_up_to` on the error, slice the string up to the returned index, and then parse again. If one is not searching URIs in a string with brute force (so that they try all possible starting indexes), I don't have an immediate idea how a `valid_up_to` method can be useful. Would you elaborate on why it is useful, perhaps with another example or from another perspective?

**Comment by Anatoly03** [comment]
Thank you for your response. Yeah, I was considering more broad contexts, but you are right, maybe scanning till a whitespace is the better approach after all.
